### PR TITLE
docs(Link): added Link to components

### PR DESCRIPTION
**Pull request by LakeVostok**
PR to uikit https://github.com/gravity-ui/uikit/pull/955

### CODE REVIEW

**Comment by LakeVostok** [comment]
These guys are breaking the Link display:
https://github.com/gravity-ui/landing/blob/main/src/styles.scss#L85
https://github.com/gravity-ui/landing/blob/main/src/vendors.scss#L2

**Comment by imsitnikov** [comment]
> These guys are breaking the Link display: https://github.com/gravity-ui/landing/blob/main/src/styles.scss#L85 https://github.com/gravity-ui/landing/blob/main/src/vendors.scss#L2

@LakeVostok 

1) You can add `a:not(.yc-link) { ... }` here – https://github.com/gravity-ui/landing/blob/main/src/styles.scss#L85 
2) Copy `github-markdown-dark.css` to `src/github-markdown-dark.css` and add `:not(...)` to `.markdown-body a:not(.yc-link) { ... }`. For disabling stylelint you can add `/* stylelint-disable */` at the first line. And after that delete npm package `github-markdown-css` plz.

**Comment by LakeVostok** [comment]
> > These guys are breaking the Link display: https://github.com/gravity-ui/landing/blob/main/src/styles.scss#L85 https://github.com/gravity-ui/landing/blob/main/src/vendors.scss#L2
> 
> @LakeVostok
> 
> 1. You can add `a:not(.yc-link) { ... }` here – https://github.com/gravity-ui/landing/blob/main/src/styles.scss#L85
> 2. Copy `github-markdown-dark.css` to `src/github-markdown-dark.css` and add `:not(...)` to `.markdown-body a:not(.yc-link) { ... }`. For disabling stylelint you can add `/* stylelint-disable */` at the first line. And after that delete npm package `github-markdown-css` plz.

Done

**Comment by imsitnikov** [comment]
> Done

1) Plz add `/* stylelint-disable */` to the first line of `./github-markdown-dark.css`.
2) Try to run `npm run lint`, it will show a eslint error.
3) Pull `main` and  run `npm ci`, it will install `husky` with precommit checks.

**Comment by imsitnikov** [comment]
> > 1. /* stylelint-disable *
> 
> sry. done this btw looks like project isn't work correctly on different platforms. On windows i have issue with svg, also I already had husky hooks installed and it didn't worked, so I was able to push code with eslint errors. vscode's highlighting is also not working(in other project it works)

What is the issue with svg?

**Comment by LakeVostok** [comment]
> > > 1. /* stylelint-disable *
> > 
> > 
> > sry. done this btw looks like project isn't work correctly on different platforms. On windows i have issue with svg, also I already had husky hooks installed and it didn't worked, so I was able to push code with eslint errors. vscode's highlighting is also not working(in other project it works)
> 
> What is the issue with svg?

https://github.com/gravity-ui/landing/issues/77

**Review by imsitnikov — APPROVED** [review]

**Pull request merged**
