### PR TITLE
feat(Calendar): add documentation for Calendar

### PR DESCRIPTION
**Pull request by Arucard89**
- added landing and sandbox for Calendar
- made improvements for DateField landing

### CODE REVIEW

**Comment by Arucard89** [comment]
connected with  https://github.com/gravity-ui/date-components/pull/38 and should be merged after updating date-components version in package.json

**Review by korvin89 — APPROVED** [review]

**Comment by imsitnikov** [comment]
> connected with [gravity-ui/date-components#38](https://github.com/gravity-ui/date-components/pull/38) and should be merged after updating date-components version in package.json
> 
> UPD: it's not necessary. There was no code changes in date-components which could affect the landing

Are you sure this isn't necessary? The calendar page now looks like this:

image

**Comment by Arucard89** [comment]
> > connected with [gravity-ui/date-components#38](https://github.com/gravity-ui/date-components/pull/38) and should be merged after updating date-components version in package.json
> > UPD: it's not necessary. There was no code changes in date-components which could affect the landing
> 
> Are you sure this isn't necessary? The calendar page now looks like this:
> 
> image

yes, you're right. I thought that landing got readme version from main branch. but now I see that it get specified package version for readme(https://github.com/gravity-ui/landing/blob/main/src/content/components/utils.ts#L25).

By the way, may be it will better to get readme from main/master branch? In this case you don't need to check versions of all libraries and update landing version every time when included library bump up it's version.

**Comment by imsitnikov** [comment]
> By the way, may be it will better to get readme from main/master branch? In this case you don't need to check versions of all libraries and update landing version every time when included library bump up it's version.

No, this is a bad way. The `main/master` branch may contain examples for the next lib version (in README.md), and these examples may not be rendered by current lib version from `package.json` on the landing.

**Pull request merged**
